
version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: haraj
      POSTGRES_PASSWORD: haraj
      POSTGRES_DB: haraj
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: harajaccess
      MINIO_ROOT_PASSWORD: harajsecret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    env_file: ../.env.example
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "8080:8080"

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8080
    depends_on:
      - api
    ports:
      - "3000:3000"

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
      - api
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  pgdata:
  miniodata:
